export default {
  login: 'tRomanowski',
  id: 98756387,
  node_id: 'U_kgDOBeLnIw',
  avatar_url: 'https://avatars.githubusercontent.com/u/98756387?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/tRomanowski',
  html_url: 'https://github.com/tRomanowski',
  followers_url: 'https://api.github.com/users/tRomanowski/followers',
  following_url:
    'https://api.github.com/users/tRomanowski/following{/other_user}',
  gists_url: 'https://api.github.com/users/tRomanowski/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/tRomanowski/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/tRomanowski/subscriptions',
  organizations_url: 'https://api.github.com/users/tRomanowski/orgs',
  repos_url: 'https://api.github.com/users/tRomanowski/repos',
  events_url: 'https://api.github.com/users/tRomanowski/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/tRomanowski/received_events',
  type: 'User',
  site_admin: false,
  name: 'Tim Romanowski',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 12,
  following: 20,
  created_at: '2022-01-31T14:34:35Z',
  updated_at: '2022-08-10T09:44:34Z',
  // login: 'john-smilga',
  // id: 42133389,
  // node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  // avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  // gravatar_id: '',
  // url: 'https://api.github.com/users/john-smilga',
  // html_url: 'https://github.com/john-smilga',
  // followers_url: 'https://api.github.com/users/john-smilga/followers',
  // following_url:
  //   'https://api.github.com/users/john-smilga/following{/other_user}',
  // gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  // starred_url:
  //   'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  // subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  // organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  // repos_url: 'https://api.github.com/users/john-smilga/repos',
  // events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  // received_events_url:
  //   'https://api.github.com/users/john-smilga/received_events',
  // type: 'User',
  // site_admin: false,
  // name: 'John Smilga',
  // company: 'Coding Addict',
  // blog: 'www.johnsmilga.com',
  // location: 'Los Angeles',
  // email: null,
  // hireable: null,
  // bio: 'Creator of Coding Addict',
  // twitter_username: 'john_smilga',
  // public_repos: 152,
  // public_gists: 0,
  // followers: 1495,
  // following: 0,
  // created_at: '2018-08-06T06:48:23Z',
  // updated_at: '2020-07-08T05:01:32Z',
};
